version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PWD} 
      POSTGRES_DB: ${DB_NAME} 
    networks:
        - temp_net

networks:
  temp_net:
